M48
; DRILL file KiCad 10.0.5 date 2026-08-15T10:53:29
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-08-15T10:53:29-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1457
%
G90
G05
T1
X6.57Y-2.98
T2
X4.12Y-2.97
X7.21Y-3.03
M30
